server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 101.43.104.30
    port: 6399
    password: 1qaz!QAZ
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null  # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.dabing.planabc.entity # 别名扫描包
logging:
  level:
    com.dabing.planabc: debug
  pattern:
    dateformat: mm:ss.SSS

# 设置热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
